import 'package:flutter/foundation.dart';
import 'domain/models.dart';
import 'services/address_parser.dart';import 'services/package_service.dart';import 'services/local_store.dart';import 'services/nominatim_geocoding_service.dart';import 'services/route_engine.dart';import 'services/cep_service.dart';import 'services/bounded_async.dart';
class AppState extends ChangeNotifier {
 final store=LocalStore();final geocoder=NominatimGeocodingService();final routeEngine=RouteEngine();final CepService cepService=ViaCepService();late final PackageService packageService=PackageService(AddressParser());List<DeliveryPackage> packages=[];bool loading=true,locating=false,routeOptimized=false;int lastLocateAttempted=0,lastLocateSucceeded=0,lastLocateFailed=0;
 int get reviewCount=>packages.where((p)=>p.status!=DeliveryStatus.delivered&&p.address.validation!=ValidationStatus.confirmed).length;int get deliveredCount=>packages.where((p)=>p.status==DeliveryStatus.delivered).length;int get locatedCount=>packages.where((p)=>p.status!=DeliveryStatus.delivered&&p.address.latitude!=null&&p.address.longitude!=null).length;int get retryCount=>packages.where((p)=>p.status==DeliveryStatus.absent||p.status==DeliveryStatus.addressProblem||p.status==DeliveryStatus.skipped).length;
 Future<void> init()async{packages=await store.load();routeOptimized=await store.loadRouteOptimized();loading=false;notifyListeners();}
 Future<void> addFromText(String text,{String? trackingCode})async{var p=packageService.fromOcr(text,packages,trackingCode:trackingCode);p=p.copyWith(address:await _enrichCep(p.address));packages=_clearLoadLabels([...packages,p]);routeOptimized=false;await _persist();if(p.address.validation==ValidationStatus.confirmed)await locateConfirmed();}
 Future<int> addManyFromText(String text)async{final lines=text.split(RegExp(r'\r?\n')).map((e)=>e.trim()).where((e)=>e.isNotEmpty).toList();final parsed=<DeliveryPackage>[];var known=[...packages];for(final line in lines){try{final p=packageService.fromOcr(line,[...known,...parsed]);parsed.add(p);}catch(_){}}final enriched=await mapBounded(parsed,(p)async=>p.copyWith(address:await _enrichCep(p.address)),concurrency:4);if(enriched.isNotEmpty)packages=_clearLoadLabels([...packages,...enriched]);routeOptimized=false;await _persist();if(packages.any((p)=>p.address.validation==ValidationStatus.confirmed&&p.address.latitude==null))await locateConfirmed();return enriched.length;}
 Future<AddressData> _enrichCep(AddressData a)async{if(a.cep==null||a.cep!.replaceAll(RegExp(r'\D'),'').length!=8)return a;try{final c=await cepService.lookup(a.cep!);if(c==null)return a;final number=a.number?.trim();final hasNumber=number?.isNotEmpty==true;return AddressData(raw:a.raw,street:c.street.isNotEmpty?c.street:a.street,number:number,complement:a.complement,neighborhood:c.neighborhood.isNotEmpty?c.neighborhood:a.neighborhood,city:c.city.isNotEmpty?c.city:a.city,state:c.state.isNotEmpty?c.state:a.state,cep:c.cep,latitude:a.latitude,longitude:a.longitude,confidence:hasNumber?1.0:.70,validation:hasNumber?ValidationStatus.confirmed:ValidationStatus.needsReview);}catch(_){return a;}}
 Future<void> addStructured(AddressData address)async{final p=packageService.fromOcr(address.raw,packages);packages=_clearLoadLabels([...packages,p.copyWith(address:address)]);routeOptimized=false;await _persist();if(address.validation==ValidationStatus.confirmed)await locateConfirmed();}
 Future<void> updateAddress(int index,AddressData address)async{final p=packages[index];packages=[...packages]..[index]=p.copyWith(address:address);packages=_clearLoadLabels(packages);routeOptimized=false;await _persist();if(address.validation==ValidationStatus.confirmed)await locateConfirmed();}
 Future<void> update(int index,DeliveryPackage value)async{packages=[...packages]..[index]=value;await _persist();}
 Future<void> reorder(int oldIndex,int newIndex)async{final x=[...packages];if(newIndex>oldIndex)newIndex--;final p=x.removeAt(oldIndex);x.insert(newIndex,p);packages=_clearLoadLabels(x);routeOptimized=false;await _persist();}
 Future<void> locateConfirmed()async{if(locating)return;locating=true;lastLocateSucceeded=0;lastLocateFailed=0;final candidates=<int>[];for(var i=0;i<packages.length;i++){final p=packages[i];if(p.status!=DeliveryStatus.delivered&&p.address.validation==ValidationStatus.confirmed&&(p.address.latitude==null||p.address.longitude==null))candidates.add(i);}lastLocateAttempted=candidates.length;notifyListeners();final out=[...packages];for(final i in candidates){final p=out[i];try{final a=await geocoder.locate(p.address);if(a.latitude!=null&&a.longitude!=null){out[i]=p.copyWith(address:a);lastLocateSucceeded++;}else{lastLocateFailed++;}}catch(_){lastLocateFailed++;}notifyListeners();}packages=out;locating=false;await _persist();}
 Future<void> optimizeFrom(double lat,double lng)async{final activeStatuses={DeliveryStatus.pending,DeliveryStatus.current,DeliveryStatus.absent,DeliveryStatus.addressProblem};final finished=packages.where((p)=>!activeStatuses.contains(p.status)).toList();final active=packages.where((p)=>activeStatuses.contains(p.status)).toList();packages=[...finished,..._optimize(active,lat,lng)];routeOptimized=true;await _persist();}
 List<DeliveryPackage> _optimize(List<DeliveryPackage> active,double lat,double lng){final pinned=<int,DeliveryPackage>{};final free=<DeliveryPackage>[];for(var i=0;i<active.length;i++){if(active[i].pinned){pinned[i]=active[i];}else{free.add(active[i]);}}final optimized=routeEngine.optimize(free,startLat:lat,startLng:lng);for(final e in pinned.entries){optimized.insert(e.key.clamp(0,optimized.length),e.value);}return optimized;}
 Future<int> prepareRetryRoute(double lat,double lng,{bool includeAddressProblems=false,bool includeSkipped=false})async{final retry=packages.where((p)=>p.status==DeliveryStatus.absent||(includeAddressProblems&&p.status==DeliveryStatus.addressProblem)||(includeSkipped&&p.status==DeliveryStatus.skipped)).toList();if(retry.isEmpty)return 0;final ids=retry.map((p)=>p.id).toSet();final reset=retry.map((p)=>p.copyWith(status:DeliveryStatus.pending,clearCompletedAt:true)).toList();final optimized=_optimize(reset,lat,lng);final untouched=packages.where((p)=>!ids.contains(p.id)).toList();packages=_clearLoadLabels([...untouched,...optimized]);routeOptimized=true;await _persist();return optimized.length;}
 Future<void> organizePhysicalLoad({int groupSize=20,bool overwrite=false})async{if(groupSize<1)throw ArgumentError.value(groupSize,'groupSize');if(!routeOptimized)throw StateError('Otimize a rota antes de organizar a carga.');var activeIndex=0;final out=<DeliveryPackage>[];for(final p in packages){final active=p.status==DeliveryStatus.pending||p.status==DeliveryStatus.current||p.status==DeliveryStatus.absent||p.status==DeliveryStatus.addressProblem;if(!active){out.add(p);continue;}final zoneIndex=activeIndex~/groupSize;final position=activeIndex%groupSize+1;final zone='${_zoneName(zoneIndex)}-${position.toString().padLeft(2,'0')}';out.add((overwrite||p.physicalZone?.trim().isNotEmpty!=true)?p.copyWith(physicalZone:zone):p);activeIndex++;}packages=out;await _persist();}
 List<DeliveryPackage> _clearLoadLabels(List<DeliveryPackage> source)=>source.map((p)=>p.status==DeliveryStatus.delivered?p:p.copyWith(clearPhysicalZone:true)).toList();
 String _zoneName(int index){var n=index+1;var name='';while(n>0){n--;name=String.fromCharCode(65+(n%26))+name;n~/=26;}return name;}
 Future<void> clear()async{packages=[];routeOptimized=false;lastLocateAttempted=lastLocateSucceeded=lastLocateFailed=0;await store.clear();notifyListeners();}Future<void> _persist()async{await store.save(packages,routeOptimized:routeOptimized);notifyListeners();}
}
