import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'app_state.dart';
import 'domain/models.dart';
import 'services/navigation_service.dart';
import 'screens/scanner_screen.dart';
import 'screens/prepare_route_screen.dart';
import 'screens/address_editor_dialog.dart';

void main()=>runApp(const DeliveryApp());
class DeliveryApp extends StatefulWidget{const DeliveryApp({super.key});@override State<DeliveryApp> createState()=>_DeliveryAppState();}
class _DeliveryAppState extends State<DeliveryApp>{final state=AppState();@override void initState(){super.initState();state.init();}@override Widget build(BuildContext context)=>MaterialApp(debugShowCheckedModeBanner:false,title:'Rotas Entregas',theme:ThemeData(useMaterial3:true,colorSchemeSeed:Colors.indigo),home:HomePage(state:state));}
class HomePage extends StatefulWidget{final AppState state;const HomePage({super.key,required this.state});@override State<HomePage> createState()=>_HomePageState();}
class _HomePageState extends State<HomePage>{
 @override Widget build(BuildContext context)=>AnimatedBuilder(animation:widget.state,builder:(context,_){final s=widget.state;if(s.loading)return const Scaffold(body:Center(child:CircularProgressIndicator()));return Scaffold(appBar:AppBar(title:const Text('Minha rota'),actions:[PopupMenuButton<String>(tooltip:'Adicionar',icon:const Icon(Icons.add_box_outlined),onSelected:(v){if(v=='manual')_manual(context);if(v=='paste')_pasteList(context);},itemBuilder:(_)=>const [PopupMenuItem(value:'manual',child:ListTile(leading:Icon(Icons.edit_location_alt_outlined),title:Text('Adicionar endereço'))),PopupMenuItem(value:'paste',child:ListTile(leading:Icon(Icons.content_paste),title:Text('Colar lista')))]),PopupMenuButton<String>(tooltip:'Mais opções',onSelected:(v){if(v=='clear')_confirmClear(context);},itemBuilder:(_)=>const [PopupMenuItem(value:'clear',child:ListTile(leading:Icon(Icons.delete_outline),title:Text('Limpar todos os pacotes')))])]),floatingActionButton:FloatingActionButton.extended(onPressed:()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>ScannerScreen(state:s))),icon:const Icon(Icons.camera_alt),label:const Text('Escanear')),body:Column(children:[Padding(padding:const EdgeInsets.all(16),child:Row(children:[Expanded(child:_stat('${s.packages.length}','Pacotes')),Expanded(child:_stat('${s.reviewCount}','Revisar')),Expanded(child:_stat('${s.locatedCount}','Localizados'))])),if(s.packages.isNotEmpty)Padding(padding:const EdgeInsets.symmetric(horizontal:16),child:SizedBox(width:double.infinity,child:FilledButton.icon(onPressed:()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>PrepareRouteScreen(state:s))),icon:const Icon(Icons.route),label:const Padding(padding:EdgeInsets.all(12),child:Text('PREPARAR ROTA'))))),if(s.reviewCount>0)Padding(padding:const EdgeInsets.fromLTRB(16,8,16,0),child:SizedBox(width:double.infinity,child:OutlinedButton.icon(onPressed:()=>_reviewNext(context),icon:const Icon(Icons.warning_amber),label:Text('REVISAR ${s.reviewCount} ENDEREÇO${s.reviewCount==1?'':'S'}')))),if(s.packages.isEmpty)const Expanded(child:Center(child:Text('Nenhum pacote ainda.\nToque em Escanear para começar.',textAlign:TextAlign.center)))else Expanded(child:ReorderableListView.builder(itemCount:s.packages.length,onReorder:s.reorder,itemBuilder:(context,i){final p=s.packages[i];return ListTile(key:ValueKey(p.id),leading:CircleAvatar(child:Text('${i+1}')),title:Text('${p.label}${p.physicalZone==null?'':' • 📦 ${p.physicalZone}'}'),subtitle:Text([if(p.shortTracking!=null)'Código ${p.shortTracking}',p.address.formatted.isEmpty?p.address.raw:p.address.formatted].join(' • '),maxLines:2,overflow:TextOverflow.ellipsis),trailing:Icon(p.address.validation==ValidationStatus.confirmed?Icons.check_circle:Icons.warning_amber),onTap:()=>_package(context,i,p));}))]));});
 Widget _stat(String n,String t)=>Column(children:[Text(n,style:const TextStyle(fontSize:24,fontWeight:FontWeight.bold)),Text(t)]);
 Future<void> _manual(BuildContext context)async{final r=await showAddressEditor(context,title:'Adicionar endereço');if(r!=null&&r.raw.isNotEmpty)await widget.state.addStructured(r.toAddress());}
 Future<void> _edit(BuildContext context,int i,DeliveryPackage p)async{final r=await showAddressEditor(context,title:p.address.validation==ValidationStatus.confirmed?'Editar endereço':'Revisar ${p.label}',initial:p.address);if(r!=null&&r.raw.isNotEmpty)await widget.state.updateAddress(i,r.toAddress());}
 Future<void> _reviewNext(BuildContext context)async{final i=widget.state.packages.indexWhere((p)=>p.address.validation!=ValidationStatus.confirmed);if(i>=0)await _edit(context,i,widget.state.packages[i]);}
 Future<void> _physicalZone(BuildContext context,int i,DeliveryPackage p)async{final c=TextEditingController(text:p.physicalZone??'');final ok=await showDialog<bool>(context:context,builder:(d)=>AlertDialog(title:Text('Onde está ${p.label}?'),content:TextField(controller:c,autofocus:true,textCapitalization:TextCapitalization.characters,decoration:const InputDecoration(labelText:'Caixa, setor ou posição',hintText:'Ex.: Caixa A, porta-malas, banco traseiro',border:OutlineInputBorder())),actions:[TextButton(onPressed:()=>Navigator.pop(d,false),child:const Text('Cancelar')),FilledButton(onPressed:()=>Navigator.pop(d,true),child:const Text('Salvar'))]));if(ok==true){final value=c.text.trim();await widget.state.update(i,p.copyWith(physicalZone:value.isEmpty?null:value));}c.dispose();}
 Future<void> _pasteList(BuildContext context)async{final c=TextEditingController();final clip=await Clipboard.getData(Clipboard.kTextPlain);if(clip?.text?.trim().isNotEmpty==true)c.text=clip!.text!;if(!context.mounted)return;final ok=await showDialog<bool>(context:context,builder:(d)=>AlertDialog(title:const Text('Colar lista de endereços'),content:SizedBox(width:500,child:TextField(controller:c,minLines:8,maxLines:14,decoration:const InputDecoration(hintText:'Cole todos de uma vez.\nUse um endereço por linha.',border:OutlineInputBorder()))),actions:[TextButton(onPressed:()=>Navigator.pop(d,false),child:const Text('Cancelar')),FilledButton.icon(onPressed:()=>Navigator.pop(d,true),icon:const Icon(Icons.playlist_add),label:const Text('Adicionar lista'))]));if(ok==true&&c.text.trim().isNotEmpty){final n=await widget.state.addManyFromText(c.text);if(context.mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text('$n endereços adicionados. Revise os que estiverem com ⚠️.')));}c.dispose();}
 Future<void> _confirmClear(BuildContext context)async{final ok=await showDialog<bool>(context:context,builder:(d)=>AlertDialog(title:const Text('Limpar todos os pacotes?'),content:Text('Isso apagará os ${widget.state.packages.length} pacotes desta rota. Esta ação não pode ser desfeita.'),actions:[TextButton(onPressed:()=>Navigator.pop(d,false),child:const Text('Cancelar')),FilledButton(onPressed:()=>Navigator.pop(d,true),child:const Text('Apagar tudo'))]));if(ok==true)await widget.state.clear();}
 Future<void> _package(BuildContext context,int i,DeliveryPackage p)async{await showModalBottomSheet(context:context,builder:(c)=>SafeArea(child:Wrap(children:[ListTile(title:Text(p.label),subtitle:Text([if(p.shortTracking!=null)'Código: ${p.shortTracking}',p.address.formatted.isEmpty?p.address.raw:p.address.formatted].join('\n'))),ListTile(leading:const Icon(Icons.inventory_2_outlined),title:Text(p.physicalZone==null?'Definir local físico':'Local físico: ${p.physicalZone}'),subtitle:const Text('Caixa, setor ou posição no veículo'),onTap:(){Navigator.pop(c);_physicalZone(context,i,p);}),ListTile(leading:Icon(p.address.validation==ValidationStatus.confirmed?Icons.edit_location_alt:Icons.warning_amber),title:Text(p.address.validation==ValidationStatus.confirmed?'Editar endereço':'Revisar endereço'),onTap:(){Navigator.pop(c);_edit(context,i,p);}),ListTile(leading:const Icon(Icons.navigation),title:const Text('Abrir no Waze'),onTap:(){Navigator.pop(c);NavigationService().openWaze(p);}),ListTile(leading:const Icon(Icons.check),title:const Text('Marcar entregue'),onTap:(){Navigator.pop(c);widget.state.update(i,p.copyWith(status:DeliveryStatus.delivered));}),ListTile(leading:const Icon(Icons.person_off),title:const Text('Destinatário ausente'),onTap:(){Navigator.pop(c);widget.state.update(i,p.copyWith(status:DeliveryStatus.absent));}),ListTile(leading:const Icon(Icons.push_pin),title:Text(p.pinned?'Desafixar parada':'Fixar parada'),onTap:(){Navigator.pop(c);widget.state.update(i,p.copyWith(pinned:!p.pinned));})])));}
}
