import 'package:flutter/material.dart';
import '../app_state.dart';
import '../domain/models.dart';
import '../services/location_service.dart';
import 'map_screen.dart';
import 'delivery_screen.dart';

class PrepareRouteScreen extends StatelessWidget{
 final AppState state; const PrepareRouteScreen({super.key,required this.state});
 bool _routeActive(DeliveryPackage p)=>p.status==DeliveryStatus.pending||p.status==DeliveryStatus.current||p.status==DeliveryStatus.absent||p.status==DeliveryStatus.addressProblem;
 Future<void> _locate(BuildContext c)async{if(state.reviewCount>0){ScaffoldMessenger.of(c).showSnackBar(SnackBar(content:Text('Revise ${state.reviewCount} endereço${state.reviewCount==1?'':'s'} antes de preparar a rota.')));return;}await state.locateConfirmed();if(c.mounted)ScaffoldMessenger.of(c).showSnackBar(SnackBar(content:Text('${state.locatedCount} endereços prontos para a rota.')));}
 Future<void> _optimize(BuildContext c)async{try{final p=await LocationService().current();await state.optimizeFrom(p.latitude,p.longitude);if(c.mounted)ScaffoldMessenger.of(c).showSnackBar(const SnackBar(content:Text('Rota otimizada a partir da sua posição.')));}catch(e){if(c.mounted)ScaffoldMessenger.of(c).showSnackBar(SnackBar(content:Text('$e')));}}
 Future<void> _organizeLoad(BuildContext c)async{final result=await showDialog<int>(context:c,builder:(_)=>const _LoadDialog());if(result!=null&&result>0){await state.organizePhysicalLoad(groupSize:result,overwrite:true);if(c.mounted)ScaffoldMessenger.of(c).showSnackBar(const SnackBar(content:Text('Carga organizada conforme a rota.')));}}
 @override Widget build(BuildContext context)=>AnimatedBuilder(animation:state,builder:(context,_){
   final activePackages=state.packages.where(_routeActive).toList();final active=activePackages.length;final located=activePackages.where((p)=>p.address.latitude!=null&&p.address.longitude!=null).length;final unresolved=active-located;final review=activePackages.where((p)=>p.address.validation!=ValidationStatus.confirmed).length;final allReady=active>0&&review==0&&unresolved==0;final canLocate=review==0&&unresolved>0;final canOptimize=allReady&&active>=2;final canOrganize=state.routeOptimized&&allReady;final canMap=located>0;final canStart=allReady&&(active==1||state.routeOptimized);
   return Scaffold(appBar:AppBar(title:const Text('Preparar rota')),body:ListView(padding:const EdgeInsets.all(16),children:[Card(child:Padding(padding:const EdgeInsets.all(18),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('$active pacotes ativos',style:Theme.of(context).textTheme.headlineSmall),const SizedBox(height:4),Text('$review precisam de revisão • $located de $active localizados'),if(unresolved>0)Padding(padding:const EdgeInsets.only(top:6),child:Text('$unresolved ainda não ${unresolved==1?'foi localizado':'foram localizados'}',style:TextStyle(color:Theme.of(context).colorScheme.error,fontWeight:FontWeight.w600))),if(state.routeOptimized&&allReady&&active>1)const Padding(padding:EdgeInsets.only(top:6),child:Row(children:[Icon(Icons.check_circle_outline,size:18),SizedBox(width:6),Text('Rota otimizada e pronta')])),if(state.locating)...[const SizedBox(height:10),const LinearProgressIndicator(),const SizedBox(height:6),const Text('Localizando endereços automaticamente...')]]))),const SizedBox(height:12),if(unresolved>0)FilledButton.icon(onPressed:state.locating||!canLocate?null:()=>_locate(context),icon:const Icon(Icons.location_searching),label:const Padding(padding:EdgeInsets.all(14),child:Text('LOCALIZAR PENDENTES'))),if(unresolved>0)const SizedBox(height:10),FilledButton.tonalIcon(onPressed:canOptimize?()=>_optimize(context):null,icon:Icon(state.routeOptimized?Icons.check_circle:Icons.route),label:Padding(padding:const EdgeInsets.all(14),child:Text(state.routeOptimized?'1. ROTA OTIMIZADA • REOTIMIZAR':'1. OTIMIZAR ROTA'))),const SizedBox(height:10),FilledButton.tonalIcon(onPressed:canOrganize?()=>_organizeLoad(context):null,icon:const Icon(Icons.inventory_2_outlined),label:const Padding(padding:EdgeInsets.all(14),child:Text('2. ORGANIZAR CARGA'))),const SizedBox(height:10),OutlinedButton.icon(onPressed:canMap?()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>RouteMapScreen(packages:state.packages))):null,icon:const Icon(Icons.map),label:const Padding(padding:EdgeInsets.all(14),child:Text('3. VER MAPA'))),const SizedBox(height:24),FilledButton.icon(onPressed:canStart?()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>DeliveryScreen(state:state))):null,icon:const Icon(Icons.play_arrow),label:const Padding(padding:EdgeInsets.all(16),child:Text('INICIAR ENTREGAS'))),if(review>0)const Padding(padding:EdgeInsets.only(top:10),child:Text('Confirme os endereços marcados com ⚠️ antes de preparar a rota.',textAlign:TextAlign.center))else if(unresolved>0&&!state.locating)Padding(padding:const EdgeInsets.only(top:10),child:Text('Faltam $unresolved endereço${unresolved==1?'':'s'} no mapa. A rota não será iniciada deixando pacote para trás.',textAlign:TextAlign.center))else if(active>1&&!state.routeOptimized)const Padding(padding:EdgeInsets.only(top:10),child:Text('Todos os endereços estão localizados. Agora otimize a rota antes de iniciar.',textAlign:TextAlign.center))]));});
}

class _LoadDialog extends StatefulWidget{const _LoadDialog();@override State<_LoadDialog> createState()=>_LoadDialogState();}
class _LoadDialogState extends State<_LoadDialog>{late final TextEditingController controller;@override void initState(){super.initState();controller=TextEditingController(text:'20');}@override void dispose(){controller.dispose();super.dispose();}@override Widget build(BuildContext context)=>AlertDialog(title:const Text('Organizar carga'),content:Column(mainAxisSize:MainAxisSize.min,crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('A organização seguirá a rota otimizada. Não existe limite fixo de pacotes.'),const SizedBox(height:14),TextField(controller:controller,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'Pacotes por grupo',helperText:'20 é apenas o padrão; você pode escolher outro.',border:OutlineInputBorder()))]),actions:[TextButton(onPressed:()=>Navigator.pop(context),child:const Text('Cancelar')),FilledButton(onPressed:()=>Navigator.pop(context,int.tryParse(controller.text)),child:const Text('Organizar'))]);}
